#!/usr/bin/env bash
current=$(pwd)
if [ ! -f "${current}/docker-compose.yml" ]; then
  echo "Expected that this script would be called from the docker-compose.yml directory"
fi
docker_compose_prefix=$(basename "${current}")
docker_compose_network=$(sed -n "/networks:/{n;s/\s//g;s/://;p}" "${current}/docker-compose.yml")
join_network="${docker_compose_prefix}_${docker_compose_network}"

filepath="$(realpath -s "$1")"
INSTRUMENT_DIR=$(dirname "$filepath")
INSTRUMENT="$(basename "$filepath")"
# Remove 'mcbifrost' and {instrument file}:
shift
export ARGUMENTS="$*"

echo "Execute instrument ${INSTRUMENT} in directory ${INSTRUMENT_DIR} with arguments ${ARGUMENTS}"

now=$(date -u +%Y%m%dT%H%M%S)
filename="${INSTRUMENT}_${now}.h5"


broker="broker:29092"
FORWARDER_CONFIG="ForwardConfig"
WRITER_COMMAND="WriterCommand"
WRITER_JOB="WriterJob"
EVENT_SOURCE="caen"
EVENT_TOPIC="SimulatedEvents"
PARAMETER_TOPIC="SimulatedParameters"
prefix="mcstas:"
work="/work/"

NEXUS_STRUCTURE="bifrost_nxs_output.json"  # this is bad.
#NEXUS_STRUCTURE="minimal_streams.json"

# provide options for the in-container bash script, then all mcrun arguments following '--'
podman run --network="${join_network}"\
  --cap-add=NET_ADMIN --cap-add=NET_RAW\
  -v "${INSTRUMENT_DIR}/:${work}:Z" -v "${current}:/extra:Z" \
  --entrypoint "/extra/entrypoint-mcstas-plus.sh"\
  mcstas-plus\
	-b ${broker} -w ${work} -p ${prefix} -c ${FORWARDER_CONFIG}\
	-o ${WRITER_COMMAND} -j ${WRITER_JOB} --event-source ${EVENT_SOURCE} --event-topic ${EVENT_TOPIC}\
	--parameter-topic ${PARAMETER_TOPIC} --filename "${filename}"\
	--nexus-structure "/extra/${NEXUS_STRUCTURE}"\
	-- "${INSTRUMENT}" ${ARGUMENTS}


# The writer stores its file *inside* the container, but we want it outside:
echo "Copy ${filename} from the writer container to the instrument directory (it remains IN the container)"
podman cp writer:"/output/${filename}" "${INSTRUMENT_DIR}/."
